[#ftl]
[@b.head/]
[#if chooseAvtivities?? && chooseAvtivities?size>0]
	[@b.toolbar title="已选辅导活动"/]
	[@b.grid items=chooseAvtivities var="cActivity"]
	  [@b.row]
	    [@b.col width="20%" property="date" title="日期"]${(cActivity.date?string('yyyy-MM-dd'))?default('')}[/@]
	    [@b.col width="20%" title="时间"]${cActivity.beginAt! }-${cActivity.endAt }[/@]
	    [@b.col width="25%" property="subject" title="活动名称（类别）"/]
	    [@b.col width="20%" property="teacher.user.name" title="辅导教师"/]
	    [@b.col width="15%" title="操作"][@b.a href="!unChoose?activity.id=${cActivity.id}"]取消预约[/@][/@]
	  [/@]
	[/@]
[/#if]
[@b.toolbar title="可选辅导活动"/]
[#if activities?? && activities?size>0]
	[@b.grid items=activities var="activity"]
	  [@b.row]
	    [@b.col width="15%" property="date" title="日期"]${(activity.date?string('yyyy-MM-dd'))?default('')}[/@]
	    [@b.col width="15%" title="时间"]${activity.beginAt! }-${activity.endAt }[/@]
	    [@b.col width="25%" property="subject" title="活动名称（类别）"/]
	    [@b.col width="15%" property="teacher.user.name" title="辅导教师"/]
	    [@b.col width="10%" property="capacity" title="最大容量"/]
	    [@b.col width="10%" title="已选人数"]${(activity.stds.size)! }[/@]
	    [@b.col width="10%" title="操作"][@b.a href="!choose?activity.id=${activity.id}"]预约[/@][/@]
	  [/@]
	[/@]
[#else]目前没有可选辅导活动
[/#if]
[@b.foot/]