[#ftl]
[@b.head/]
[#if chooseLectures?? && chooseLectures?size>0]
	[@b.toolbar title="已选课堂活动"/]
	[@b.grid items=chooseLectures var="cLecture"]
	  [@b.row]
	    [@b.col width="15%" property="date" title="日期"]${(cLecture.date?string('yyyy-MM-dd'))?default('')}[/@]
	    [@b.col width="15%" title="时间"]${cLecture.beginAt! }-${cLecture.endAt }[/@]
	    [@b.col width="20%" property="subject" title="活动名称（类别）"/]
	    [@b.col width="20%" property="location" title="地点"]${(cLecture.room.name)!} ${cLecture.location! }[/@]
	    [@b.col width="15%" property="teachers" title="组织教师"/]
	    [@b.col width="15%" title="操作"][@b.a href="!unChoose?lecture.id=${cLecture.id}"]退选[/@][/@]
	  [/@]
	[/@]
[/#if]
[@b.toolbar title="可选课堂活动"/]
[#if lectures?? && lectures?size>0]
	[@b.grid items=lectures var="lecture"]
	  [@b.row]
	    [@b.col width="10%" property="date" title="日期"]${(lecture.date?string('yyyy-MM-dd'))?default('')}[/@]
	    [@b.col width="10%" title="时间"]${lecture.beginAt! }-${lecture.endAt }[/@]
	    [@b.col width="20%" property="subject" title="活动名称（类别）"/]
	    [@b.col width="20%" property="location" title="地点"]${(lecture.room.name)!} ${lecture.location! }[/@]
	    [@b.col width="10%" property="teachers" title="组织教师"/]
	    [@b.col width="10%" property="capacity" title="最大容量"/]
	    [@b.col width="10%" title="已选人数"]${(lecture.audiences.size)! }[/@]
	    [@b.col width="10%" title="操作"][@b.a href="!choose?lecture.id=${lecture.id}"]选择[/@][/@]
	  [/@]
	[/@]
[#else]目前没有可选课堂活动
[/#if]
[@b.foot/]